config/routes.rb
Skillmanagementsystem::Application.routes.draw do
	match 'ocreate', :controller => 'organization', :action => 'orgcreate'
	match 'orgsave', :controller => 'organization', :action => 'orgsave'
	match 'oview', :controller => 'organization', :action => 'view'
	match 'oviewgrp', :controller => 'organization', :action => 'viewgrp'
	match 'show', :controller => 'organization', :action => 'show'
	match 'allorgshow', :controller => 'organization', :action => 'allorgshow'
	match 'orgdestroy', :controller => 'organization', :action => 'orgdestroy'
	match 'orgedit/:oid', :controller => 'organization', :action => 'orgedit'
	match 'orgupdate', :controller => 'organization', :action => 'orgupdate'
	match 'pageper', :controller => 'organization', :action => 'pageper'
	match 'grpshow', :controller => 'organization', :action => 'grpshow'
	
	match 'gcreate', :controller => 'group', :action => 'grpcreate'
	match 'grpsave', :controller => 'group', :action => 'grpsave'
	match 'search', :controller => 'group', :action => 'search'
	match 'groupshow', :controller => 'group', :action => 'groupshow'
	match 'grpdestroy', :controller => 'group', :action => 'grpdestroy'
	match 'grpedit/:grpid', :controller => 'group', :action => 'grpedit'
	match 'grpupdate', :controller => 'group', :action => 'grpupdate'
	match 'grpallshow', :controller => 'group', :action => 'groupallshow'
	match 'groupsearch', :controller => 'group', :action => 'groupsearch'
	match 'groupskillsearch', :controller => 'group', :action => 'groupskillsearch'
	match 'groupDisplayRange', :controller => 'group', :action => 'groupDisplayRange'
	match 'groupSkillSearch', :controller => 'group', :action => 'groupSkillSearch'

	match 'pplcreate', :controller => 'person', :action => 'pplcreate'
	match 'pplsave', :controller => 'person', :action => 'pplsave'
	match 'pplshow', :controller => 'person', :action => 'pplshow'
	match 'ppldisplay', :controller => 'person', :action => 'ppldisplay'
	match 'ppldisplay/:prsnid', :controller => 'person', :action => 'ppldisplay'
	match 'ppldestroy', :controller => 'person', :action => 'ppldestroy'
	match 'ppledit/:pplid', :controller => 'person', :action => 'ppledit'
	match 'pplupdate', :controller => 'person', :action => 'pplupdate'
	match 'pplallshow', :controller => 'person', :action => 'personallshow'
	match 'peoplesearch', :controller => 'person', :action => 'peoplesearch'
	match 'peopleskillsearch', :controller => 'person', :action => 'peopleskillsearch'
	match 'peopleDisplayByPageRange', :controller => 'person', :action => 'peopleDisplayByPageRange'
	match 'peopleSkillViewSearch', :controller => 'person', :action => 'peopleSkillViewSearch'

	match 'spsave', :controller => 'skill', :action => 'spsave'
	match 'spshow', :controller => 'skill', :action => 'spshow'
	match 'sgcreate', :controller => 'skill', :action => 'sgcreate'
	match 'sgsave', :controller => 'skill', :action => 'sgsave'
	match 'sgshow', :controller => 'skill', :action => 'sgshow'
	match 'sgdisplay', :controller => 'skill', :action => 'sgdisplay'
	match 'spcreate', :controller => 'skill', :action => 'spcreate'
	match 'spdisplay', :controller => 'skill', :action => 'spdisplay'
	match 'skilldestroy', :controller => 'skill', :action => 'skilldestroy'
	match 'usrskilledit/:sid&:gid&:pid', :controller => 'skill', :action => 'usrskilledit'
	match 'usrskillupdate', :controller => 'skill', :action => 'usrskillupdate'
	match 'grpskilledit/:sid&:gid', :controller => 'skill', :action => 'grpskilledit'
	match 'groupskilledit/:sid&:gid', :controller => 'skill', :action => 'groupskilledit'
	match 'grpskillupdate', :controller => 'skill', :action => 'grpskillupdate'
	match 'skillsearch', :controller => 'skill', :action => 'skillsearch'	
	match 'skillviewsearch', :controller => 'skill', :action => 'skillviewsearch'
	match 'allGroupSkills', :controller => 'skill', :action => 'allGroupSkills'
	match 'allPersonSkills', :controller => 'skill', :action => 'allPersonSkills'

	match 'showAllSkills', :controller => 'skill', :action => 'showAllSkills'
	

   root :to => 'organization#index'

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :person
	belongs_to :groups
  attr_accessible :skill1, :skill2
end

app/controllers/skill_controller.rb
class SkillController < ApplicationController
	def sgcreate
		@skill = Skill.find(1)
		@skills = @skill.allskills
		@organization = Organization.all
		render :file => "app/views/skill/sgcreate.html.erb"
	end

	def sgsave
		cnt = params[:skills]
		skillarray = Array.new


		puts "###################### $$$$$$$$$$$$$$$$$$$$$"
		puts cnt.class.inspect
		puts cnt['sk1'].class
		puts cnt['sk1']

		#render :text => 'update'

		skillarray = cnt['sk1'].split(', ')

		puts skillarray.class
		puts skillarray.inspect
		


#		render :text => 'created'		


		@grp = Group.find(params[:grpsel])
		@skill = @grp.skills.new
		@grp.skill = skillarray
		@skill.allskills = skillarray
		@skill.save
		@grp.save
		if((@grp.save)||(@skill.save))
			flash[:notice] = 'Skills Successfully Created'
			@grp = Group.order("name").page(params[:page]).per(2)			
			redirect_to :action => "allGroupSkills"		
		end
	end

	def sgshow
		@organization = Organization.all
		render :file => "app/views/skill/sgshow.html.erb"
	end

	def sgdisplay

		puts "###########################"
		puts params[:grpsel]
		@group = Group.find(params[:grpsel])
		@skills = @group.skills.order('id desc').limit(1).all	
		puts @skills
		@skills.each do |s| 
			@allskills = s.allskills.split('-')
			@allskills.reject!{|element| element.empty?} 
			@allskills.delete_at(0)
			#@allskills.shift 
		end

		puts @allskills.inspect
		render :file => 'app/views/skill/sgdisplay.html.erb'
	end

	
	def spcreate
		@organization = Organization.all
		render :file => "app/views/skill/spcreate.html.erb"
	end

	def skillsearch
		@grp = Group.find(params[:id])
		@skills = @grp.skills.all
		@skills.each do |s| 
			@allskills = s.allskills.split('-')
			@allskills.reject!{|element| element.empty?} 
			#@allskills.shift 
		end
		render :partial => "skillssearchresult.html.erb"
	end



	before_filter :set_search

	def set_search
    #render :text => params.inspect and return
		@search=Group.search(params[:q])
		@search1 = Person.search(params[:q])
	end

	
	def allGroupSkills
		@skill = Skill.all
		@q = Group.search(params[:q])
		@groups = @q.result.order("id").page(params[:page]).per(3)
		render :file => 'app/views/skill/allgroupskills.html.erb'
	end
	
	def allPersonSkills
		@skill = Skill.all
		@q = Person.search(params[:q])
		@people = @q.result.order("id").page(params[:page]).per(3)
		render :file => 'app/views/skill/allpersonskills.html.erb'
	end


	def skillviewsearch
		@grp = Group.find(params[:id])
		@skills = @grp.skills.all
		@skills.each do |s| 
			@allskills = s.allskills.split('-')
			@allskills.reject!{|element| element.empty?} 
			@allskills.shift 
		end
		render :partial => "skillssearchresult.html.erb"
	end

	
	def spsave
		@prsn = Person.find(params[:prsnid])
		@skill = @prsn.skills.new
		@prsn.skill = params[:skills]
		@skill.allskills = params[:skills]
		@prsn.save
		@skill.save
		if((@prsn.save)||(@skill.save))
			flash[:notice] = 'Skills Successfully Created'
			redirect_to :action => "allPersonSkills"		
		end
	end

	def spshow
		@organization = Organization.all
		render :file => "app/views/skill/spshow.html.erb"
	end

	def spdisplay
		begin
		@prsn = Person.find(params[:prsnid])
		@skills = @prsn.skills.order('id asc').limit(1).all
		@skills.each do |s| 
			@allskills = s.allskills.split('-')
			@allskills.reject!{|element| element.empty?} 
			@allskills.shift
		end
		rescue
		end
		render :file => 'app/views/skill/spdisplay.html.erb'
	end

	def usrskilledit


		
		

		@prsn = Person.find(params[:pid])
		@grp = Group.find(params[:gid])
		@skills = @grp.skills.all
		#@allskills = @grp.skill.split('-').reject!{|element| element.empty?}
		@skills.each do |s| 
			@allskills = s.allskills.split('-')
			@allskills.reject!{|element| element.empty?} 
			@allskills.shift 
			
		end

		@usrskill = @prsn.skills.all
		@usrskill.each do |s| 
			@totalusrskills = s.allskills.split('-')
			@totalusrskills.reject!{|element| element.empty?} 
			@totalusrskills.shift
			
		end

			puts @allskills.inspect
			puts @totalusrskills.inspect
		@skill = Skill.find(params[:sid])
		@@sk1 = @skill
		render :file => 'app/views/skill/usrskilleditview.html.erb'
	end

	def usrskillupdate
		@@sk1.person_id = params[:prsnsel]
		@@sk1.allskills = params[:skills]
		@person = Person.find(params[:prsnsel])
		@person.skill = params[:skills]
		@person.save
		@@sk1.save

		if(@person.save)
				flash[:notice] = 'Skills Updated Successfully'
				redirect_to :action => "allPersonSkills"
		end
		
	end

	def grpskilledit
		@skill1 = Skill.find(1)
		@@skill = @skill1
		@skills1 = @skill1.allskills
		@grp = Group.find(params[:gid])
		@sk = @grp.skills.find(params[:sid])
		@@skillobj = @sk
		@skills = @grp.skills.all
		@@group = @grp
		@skills.each do |s| 
			@allskills = s.allskills.split('-')
			@allskills.reject!{|element| element.empty?} 
			#@allskills.shift 
		end
			puts @allskills.inspect

			@@previousskills = @allskills

			puts @@previousskills.inspect
			
		render :file => 'app/views/skill/grpeditview.html.erb'
	end

	def groupskilledit
		@skill1 = Skill.find(1)
		@@skill = @skill1
		@skills1 = @skill1.allskills

		@@skillobj = Skill.find(params[:sid])


		@grp = Group.find(params[:gid])
		@@group = @grp
		@allskills = @grp.skill.split('-').reject!{|element| element.empty?}
		puts @allskills.class

			@@previousskills = @allskills
			
		render :file => 'app/views/skill/grpskilleditview.html.erb'
	end



	def grpskillupdate
		cnt = params[:skills]
		skillarray = Array.new
		cnt.keys.each do |k|
			skillarray << cnt[k]
		end
	

		puts "########## Previou Values ##############"
		puts @@previousskills.inspect
		puts @@previousskills.delete_at(0)
		puts @@previousskills.class.inspect
		puts @@previousskills.inspect

		puts "########### Current Skills ##############"
		puts cnt.inspect
		puts cnt['sk1'].class	
		puts cnt['sk1'].inspect
	
		current_value = [cnt['sk1']]
		puts current_value.class
		puts current_value.inspect
				
	    @prvskill = @@previousskills
		puts "########### Skills ##############"
		updated_skills = @prvskill + current_value
		puts updated_skills.inspect


		#render :text => 'update'

		@@group.skill = updated_skills
		@@group.save

		@@skillobj.allskills = updated_skills
		@@skillobj.save
		
		redirect_to :action => "allGroupSkills"
	end

	def skilldestroy
		@personid = Person.find(params[:id])
		@personid.skill=''
		@personid.save
		if(true)
		flash[:notice] = 'Skill Successfully Deleted'
		redirect_to :action => "allPersonSkills"
		end		
	end

end

app/helpers/skill_helper.rb
module SkillHelper
end

app/views/skill/allgroupskills.html.erb
<html>
	<head>
			<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
		  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
		  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
		  <script>
				$('document').ready(function(){
				
				$('#opdelete').click(function(e){
						
					e.preventDefault();
					var va = $(this).attr("class");
					$( "#dialog-confirm" ).dialog({
					  resizable: false,
					  height:180,
					  width:400,
					  modal: true,
					  buttons: {
						"Delete": function() {
						  $( this ).dialog( "close" );
							
							  $.ajax({
				        		url: "/skilldestroy",
								data: {id: va},
				        		success: function (data) {
									$("#myid").html("successfully deleted");
									$("#myid1").html("");
				        		}
				    		   });

						 },
						"No": function() {
						  $( this ).dialog( "close" );
							return false;
						  }
						  }
					  }); 
				});				
						

});
		  </script>
	</head>
	<body>
<div id='myid1'>

	 <% if flash[:notice] %>
		    <div class="alert alert-success">  
  					<a class="close" data-dismiss="alert">&times;</a>  
					  <strong>Success!</strong> <%= flash[:notice] %>
			</div>  
		 <% end %>

	<h1>Listing Group Skills</h1>

	<div class='pull-right'>
		<%= link_to 'Create Group Skills', spcreate_path, :class=>'btn' %>
	</div>


	<table class='table table-stiped table-hover'>

		<%= search_form_for @search, :url=>'allGroupSkills' do |f| %>
			<tr>
				<td> <%= f.text_field :name_cont, :placeholder => 'Filter', :class=>'filterbox'  %>  </td>
				<td> <%= f.text_field :skill_cont, :placeholder => 'Filter', :class=>'filterbox'  %>  </td>
				<td id='mptycolumn' colspan='2'> <%= f.submit 'Filter', :class=>'btn btn-primary' %> </td>
			</tr>	
		<% end %>	
	  <tr>
		<th> Group Name </th>
		<th>Skills </th>
		<th class='opth' colspan='2'> Action </th>
		</tr>
	<% begin %>
	<% @groups.each do |g| %>
			
			<% @skill.each do |s| %>
					<% if g.id == s.group_id %>
						<% @sid = s.id %>
					<% end %>
			<% end %>
	   <tr>
		<td> <%= g.name %>  </td> 
		 <td>  <% g.skill.split('-').reject!{|element| element.empty?}. each do|g| %>
		 <%= g.gsub(' ','').gsub("'",'').gsub("\|2",'').chomp() %>   

				
			<% end %> </td>

			

			
		<td class='optd'> <a href='/groupskilledit/<%= @sid %>&<%= g.id %>' title='Click to Edit the Skills' > <img src='assets/add.png'> </a> </td>
					<td class='optd'> <%= link_to image_tag('/assets/delete.png'),skilldestroy_path(:id => g.id), :title=>'Click to Delete the Skills', :class=>g.id, :id=>'opdelete' %> </td>
	   </tr>
	<% end %>
	<% rescue %>
		<% end %>
	</table>
	</div>	
				<%= paginate @groups %>

	
		<div id="dialog-confirm" title="Do you wanna Delete this?">
  <p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>This item will be permanently deleted and cannot be recovered. Are you sure?</p> </div>

<br />
	<div class='btn'> <%= link_to 'Back', sgshow_path %> </div>
	</body>
</html>

app/views/skill/allpersonskills.html.erb
<html>
	<head>
			<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
		  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
		  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
		  <script>
				$('document').ready(function(){
				
				$('#opdelete').click(function(e){
						
					e.preventDefault();
					var va = $(this).attr("class");
					$( "#dialog-confirm" ).dialog({
					  resizable: false,
					  height:180,
					  width:400,
					  modal: true,
					  buttons: {
						"Delete": function() {
						  $( this ).dialog( "close" );
							
							  $.ajax({
				        		url: "/skilldestroy",
								data: {id: va},
				        		success: function (data) {
									$("#myid").html("successfully deleted");
									$("#myid1").html("");
				        		}
				    		   });

						 },
						"No": function() {
						  $( this ).dialog( "close" );
							return false;
						  }
						  }
					  }); 
				});				
						

});
		  </script>
	</head>
	<body>
<div id='myid1'>

	<% if flash[:notice] %>
		    <div class="alert alert-success">  
  					<a class="close" data-dismiss="alert">&times;</a>  
					  <strong>Success! </strong> <%= flash[:notice] %>
			</div>  
    <% end %>

	<h1>Listing Person Skills</h1>

	<div class='pull-right'>
		<%= link_to 'Create Person Skills', spcreate_path, :class=>'btn' %>
	</div>

	<table class='table table-stiped table-hover'>
	  <%= search_form_for @search1, :url=>'allPersonSkills' do |f| %>
			<tr>
				<td> <%= f.text_field :fname_cont, :placeholder => 'Filter', :class=>'filterbox'  %>  </td>
				<td> <%= f.text_field :skill_cont, :placeholder => 'Filter', :class=>'filterbox'  %>  </td>
				<td id='mptycolumn' colspan='2'> <%= f.submit 'Filter', :class=>'btn btn-primary' %> </td>
			</tr>	
		<% end %>	
	  <tr>
		<th> Person Name </th>
		<th>Skills </th>
		<th class='opth' colspan='2'> Action </th>
		</tr>
	<% begin %>
	<% @people.each do |p| %>
				<% @skill.each do |s| %>
					<% if p.id == s.person_id %>
						<% @sid = s.id %>
					<% end %>
			<% end %>
	   <tr>
		<td> <%= p.fname %>  </td> 
		 <td>  <% p.skill.split('-').reject!{|element| element.empty?}. each do|p| %>
		 <%= p.gsub(' ','').gsub("'",'').gsub("\|2",'').gsub('\r\n','').chomp() %>   
			<% end %> </td>
		
		<td class='optd'> <a href='/usrskilledit/<%= @sid %>&<%= p.group_id %>&<%= p.id %>' title='Click to Edit the Skills' > <img src='assets/add.png'> </a> </td>
					<td class='optd'> <%= link_to image_tag('/assets/delete.png'),skilldestroy_path(:id => p.id), :title=>'Click to Delete the Skills', :class=>p.id, :id=>'opdelete' %> </td>
	   </tr>
	<% end %>
	<% rescue %>
		<% end %>
	</table>
	</div>

		<%= paginate @people %>
	
		<div id="dialog-confirm" title="Do you wanna Delete this?">
  <p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>This item will be permanently deleted and cannot be recovered. Are you sure?</p> </div>

<br />
	<div class='btn'> <%= link_to 'Back', sgshow_path %> </div>
	</body>
</html>

app/views/skill/grpeditview.html.erb
<html>
	<head>
		<style>
			.control-label{
				float:left !important;
			}
			.span3 {
				position:absolute;
				right:400px;
			}
		</style>

<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>


		<script type="text/javascript">
				$(document).ready(function(){

							/* code for multiselect skills */
						
				var s = $('#skillvalue').val()
				
				var skills = s.split(',')	
	
				//alert(skills)
				 var availableTags = skills
					function split( val ) {
					  return val.split( /,\s*/ );
					}
					function extractLast( term ) {
					  return split( term ).pop();
					}
 
					$( "#skill" )
					  // don't navigate away from the field on tab when selecting an item
					  .bind( "keydown", function( event ) {
						if ( event.keyCode === $.ui.keyCode.TAB &&
							$( this ).data( "ui-autocomplete" ).menu.active ) {
						  event.preventDefault();
						}
					  })
					  .autocomplete({
						minLength: 0,
						source: function( request, response ) {
						  // delegate back to autocomplete, but extract the last term
						  response( $.ui.autocomplete.filter(
							availableTags, extractLast( request.term ) ) );
						},
						focus: function() {
						  // prevent value inserted on focus
						  return false;
						},
						select: function( event, ui ) {
						  var terms = split( this.value );
						  // remove the current input
						  terms.pop();
						  // add the selected item
						  terms.push( ui.item.value );
						  // add placeholder to get the comma-and-space at the end
						  terms.push( "" );
						  this.value = terms.join( ", " );
						  return false;
						}
					  });


								
				});

				function validateMe() {
					nameval = document.getElementById('sk1')
					namevalue = nameval.value
					if((namevalue == 'null') || (namevalue == ''))
						{
							document.getElementById('errormsg').innerHTML = 'Please Enter the Skill'
							nameval.focus();
								return false;
						}
						else {
							document.getElementById('errormsg').innerHTML = ''
							return true;
						}
					}		
		</script>
	</head>
	<body>
			<%= form_tag({:action => "grpskillupdate" }, :name => 'skills', :class => 'form-horizontal', :onsubmit => 'return validateMe()')  do %>
				<div class="control-group">
					<label class="control-label" for="inputId">Group Name:</label>
					<div class="controls">
							<select name='grpsel' class='span2'>
									
								<option value=<%= @grp.id %>> <%= @grp.name %> </option>
							</select>
					  </div>
			    </div>

				<input type="hidden" value=<%= @skills1 %> id="skillvalue" />

			<div class='control-group controls'>
				<% @allskills. each do|p| %>
					 <%= p.gsub(' ','').gsub("'",'').chomp() %>
			  <% end %>

			</div>
				<div class="control-group">
					<label class="control-label" for="inputsk1">Skill Name:</label>
					<div class="controls">
					  <input type="text" name ='skills[sk1]' id="skills" placeholder="SkillValue"> <span id='skillerrormsg'> </span>
					</div>
				</div>
				
			  
				
				<div class="pull-left span3">
					
					<%= submit_tag "Update", :id => "uploadid", :class => 'btn btn-primary'%>
			    </div>
	<% end %>

	<br />
<div class='btn'>		<%= link_to 'Back', sgshow_path %> </div>
 	</body>
</html>

app/views/skill/grpskilleditview.html.erb
<html>
	<head>
		<style>
			.control-label{
				float:left !important;
			}
			.span3 {
				position:absolute;
				right:400px;
			}
		</style>

<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>


		<script type="text/javascript">
				$(document).ready(function(){

							/* code for multiselect skills */
						
				var s = $('#skillvalue').val()
				
				var skills = s.split(',')	
	
				//alert(skills)
				 var availableTags = skills
					function split( val ) {
					  return val.split( /,\s*/ );
					}
					function extractLast( term ) {
					  return split( term ).pop();
					}
 
					$( "#skill" )
					  // don't navigate away from the field on tab when selecting an item
					  .bind( "keydown", function( event ) {
						if ( event.keyCode === $.ui.keyCode.TAB &&
							$( this ).data( "ui-autocomplete" ).menu.active ) {
						  event.preventDefault();
						}
					  })
					  .autocomplete({
						minLength: 0,
						source: function( request, response ) {
						  // delegate back to autocomplete, but extract the last term
						  response( $.ui.autocomplete.filter(
							availableTags, extractLast( request.term ) ) );
						},
						focus: function() {
						  // prevent value inserted on focus
						  return false;
						},
						select: function( event, ui ) {
						  var terms = split( this.value );
						  // remove the current input
						  terms.pop();
						  // add the selected item
						  terms.push( ui.item.value );
						  // add placeholder to get the comma-and-space at the end
						  terms.push( "" );
						  this.value = terms.join( ", " );
						  return false;
						}
					  });


								
				});

				function validateMe() {
					nameval = document.getElementById('sk1')
					namevalue = nameval.value
					if((namevalue == 'null') || (namevalue == ''))
						{
							document.getElementById('errormsg').innerHTML = 'Please Enter the Skill'
							nameval.focus();
								return false;
						}
						else {
							document.getElementById('errormsg').innerHTML = ''
							return true;
						}
					}		
		</script>
	</head>
	<body>
			<%= form_tag({:action => "grpskillupdate" }, :name => 'skills', :class => 'form-horizontal', :onsubmit => 'return validateMe()')  do %>
				<div class="control-group">
					<label class="control-label" for="inputId">Group Name:</label>
					<div class="controls">
							<select name='grpsel' class='span2'>
									
								<option value=<%= @grp.id %>> <%= @grp.name %> </option>
							</select>
					  </div>
			    </div>

				<input type="hidden" value=<%= @skills1 %> id="skillvalue" />

			<div class='control-group controls'>
				<%= @allskills %>

			</div>
				<div class="control-group">
					<label class="control-label" for="inputsk1">Skill Name:</label>
					<div class="controls">
					  <input type="text" name ='skills[sk1]' id="skills" placeholder="SkillValue"> <span id='skillerrormsg'> </span>
					</div>
				</div>
				
			  
				
				<div class="pull-left span3">
					
					<%= submit_tag "Update", :id => "uploadid", :class => 'btn btn-primary'%>
			    </div>
	<% end %>

	<br />
<div class='btn'>		<%= link_to 'Back', sgshow_path %> </div>
 	</body>
</html>

app/views/skill/sgdisplay.html.erb
<html>
	<head>
						<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
		  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
		  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
		  <script>
				$('document').ready(function(){
				
				$('#opdelete').click(function(e){
					
					e.preventDefault();
					var va = $(this).attr("class");
					$( "#dialog-confirm" ).dialog({
					  resizable: false,
					  height:180,
					  width:400,
					  modal: true,
					  buttons: {
						"Delete": function() {
						  $( this ).dialog( "close" );
							
							  $.ajax({
				        		url: "/skilldestroy",
								data: {id: va},
				        		success: function (data) {
									$("#myid").html("successfully deleted");
									$("#myid1").html(" ");
				        		}
				    		   });

						 },
						"No": function() {
						  $( this ).dialog( "close" );
							return false;
						  }
						  }
					  }); 
				});				
						

});
		  </script>
	</head>
	<body>
		<div id='myid1'>

		<h1>Listing Group Skills</h1>

		<div class='pull-right'>
			<%= link_to 'Add Group Skills', sgcreate_path, :class=>'btn' %>
		</div>
		

		<table class='table table-stiped table-hover'>
		  <tr>
			<th> Group Name:</th>
			<% begin %>
			<% @allskills.each do |s| %>
			<th>Skill Name</th>
			<% end %>
			<% rescue %>
			<% end %>
			<th class='opth' colspan='2'> Action </th>	
			</tr>

		<% @skills.each do |s| %>
		   <tr>
			<td> <%= @group.name %> </td>
			<% begin %>
			<% @allskills.each do |s| %>
			<td><%= sanitize(s.to_s.gsub('"',"").gsub('\r',"").gsub("\|2",'').gsub('\n',"<br/>")) %></td>
			<% end %>	
			<% rescue %>
			<% end %>
			<td class='optd'> <a href='/grpskilledit/<%= s.id %>&<%= s.group_id %>' title='Click to Edit the Skills' > <img src='assets/tab_edit.png'> </a> </td>
			<td class='optd'> <%= link_to image_tag('/assets/delete.png'), skilldestroy_path(:id=> s.id), :title=>'Click to Edit the Skills', :class=>s.id, :id=>'opdelete' %> </td>
		   </tr>
		<% end %>
		</table>
	</div>

	<div id="dialog-confirm" title="Do you wanna Delete this?">
  <p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>This item will be permanently deleted and cannot be recovered. Are you sure?</p> </div>


		<br />
<div class='btn'>			<%= link_to 'Back', sgshow_path%> </div> 

app/views/skill/success.html.erb
<h1> Success fully Created </h1>

<br />
<div class='btn'>	<%= link_to 'Create New', spcreate_path %> </div>