config/routes.rb
Skillmanagementsystem::Application.routes.draw do
	match 'ocreate', :controller => 'organization', :action => 'orgcreate'
	match 'orgsave', :controller => 'organization', :action => 'orgsave'
	match 'oview', :controller => 'organization', :action => 'view'
	match 'oviewgrp', :controller => 'organization', :action => 'viewgrp'
	match 'show', :controller => 'organization', :action => 'show'
	match 'allorgshow', :controller => 'organization', :action => 'allorgshow'
	match 'orgdestroy', :controller => 'organization', :action => 'orgdestroy'
	match 'orgedit/:oid', :controller => 'organization', :action => 'orgedit'
	match 'orgupdate', :controller => 'organization', :action => 'orgupdate'
	match 'pageper', :controller => 'organization', :action => 'pageper'
	match 'grpshow', :controller => 'organization', :action => 'grpshow'
	
	match 'gcreate', :controller => 'group', :action => 'grpcreate'
	match 'grpsave', :controller => 'group', :action => 'grpsave'
	match 'search', :controller => 'group', :action => 'search'
	match 'groupshow', :controller => 'group', :action => 'groupshow'
	match 'grpdestroy', :controller => 'group', :action => 'grpdestroy'
	match 'grpedit/:grpid', :controller => 'group', :action => 'grpedit'
	match 'grpupdate', :controller => 'group', :action => 'grpupdate'
	match 'grpallshow', :controller => 'group', :action => 'groupallshow'
	match 'groupsearch', :controller => 'group', :action => 'groupsearch'
	match 'groupskillsearch', :controller => 'group', :action => 'groupskillsearch'
	match 'groupDisplayRange', :controller => 'group', :action => 'groupDisplayRange'
	match 'groupSkillSearch', :controller => 'group', :action => 'groupSkillSearch'

	match 'pplcreate', :controller => 'person', :action => 'pplcreate'
	match 'pplsave', :controller => 'person', :action => 'pplsave'
	match 'pplshow', :controller => 'person', :action => 'pplshow'
	match 'ppldisplay', :controller => 'person', :action => 'ppldisplay'
	match 'ppldisplay/:prsnid', :controller => 'person', :action => 'ppldisplay'
	match 'ppldestroy', :controller => 'person', :action => 'ppldestroy'
	match 'ppledit/:pplid', :controller => 'person', :action => 'ppledit'
	match 'pplupdate', :controller => 'person', :action => 'pplupdate'
	match 'pplallshow', :controller => 'person', :action => 'personallshow'
	match 'peoplesearch', :controller => 'person', :action => 'peoplesearch'
	match 'peopleskillsearch', :controller => 'person', :action => 'peopleskillsearch'
	match 'peopleDisplayByPageRange', :controller => 'person', :action => 'peopleDisplayByPageRange'
	match 'peopleSkillViewSearch', :controller => 'person', :action => 'peopleSkillViewSearch'

	match 'spsave', :controller => 'skill', :action => 'spsave'
	match 'spshow', :controller => 'skill', :action => 'spshow'
	match 'sgcreate', :controller => 'skill', :action => 'sgcreate'
	match 'sgsave', :controller => 'skill', :action => 'sgsave'
	match 'sgshow', :controller => 'skill', :action => 'sgshow'
	match 'sgdisplay', :controller => 'skill', :action => 'sgdisplay'
	match 'spcreate', :controller => 'skill', :action => 'spcreate'
	match 'spdisplay', :controller => 'skill', :action => 'spdisplay'
	match 'skilldestroy', :controller => 'skill', :action => 'skilldestroy'
	match 'usrskilledit/:sid&:gid&:pid', :controller => 'skill', :action => 'usrskilledit'
	match 'usrskillupdate', :controller => 'skill', :action => 'usrskillupdate'
	match 'grpskilledit/:sid&:gid', :controller => 'skill', :action => 'grpskilledit'
	match 'groupskilledit/:sid&:gid', :controller => 'skill', :action => 'groupskilledit'
	match 'grpskillupdate', :controller => 'skill', :action => 'grpskillupdate'
	match 'skillsearch', :controller => 'skill', :action => 'skillsearch'	
	match 'skillviewsearch', :controller => 'skill', :action => 'skillviewsearch'
	match 'allGroupSkills', :controller => 'skill', :action => 'allGroupSkills'
	match 'allPersonSkills', :controller => 'skill', :action => 'allPersonSkills'

	match 'showAllSkills', :controller => 'skill', :action => 'showAllSkills'
	

   root :to => 'organization#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
	
  belongs_to :group
  belongs_to :organization
  has_many :skills, :dependent => :destroy
  attr_accessible :name, :phnum, :dob, :fname, :email
end

app/controllers/person_controller.rb
class PersonController < ApplicationController
	def pplcreate
		@organization = Organization.all
		render :file => "app/views/person/pplcreate.html.erb"
	end

	def pplsave
		@group = Group.find(params[:grpsel])
		@person = @group.people.new
		@person.organization_id = params[:orgsel]
		@person.name = params[:pplname]
		@person.phnum = params[:pplph]
		@person.dob = params[:ppldob]
		@person.fname = params[:pplfname]
		@person.place = params[:pplplace]
		@person.email = params[:pplemail]
		begin 
			file_upload = params[:pplfile]
			@person.propic = file_upload.read
			if(@person.save)
				flash[:notice] = 'Person Successfully Created'
				redirect_to :action => 'personallshow'	
			end
		rescue
			puts 'error'
		end
			
	end
	def pplshow
		@organization = Organization.all
		@prsn = Person.order("name").page(params[:page]).per(2)
		render :file => "app/views/person/pplshow.html.erb"
	end
	def ppldisplay
		@person =  Person.find(params[:prsnid])
		@skill = @person.skills.all
		@skill.each do |s| 
			@allskills = s.allskills.split('-')
			@allskills.reject!{|element| element.empty?} 
			@allskills.shift
		end
		render :file => "app/views/person/ppldisplay.html.erb"
	end

	def peoplesearch
		@group = Group.find(params[:id])
		@person = @group.people.all
		@skills = @group.skills.all


		puts "######################"
			
		#puts @skills.class.inspect
		#puts @skills.inspect
		#puts @skills[10]
		#puts @group.skill.gsub(", '\n", ",  '\n", )
		#puts @skills.allskills.inspect
			
		@skills.each do |s| 
			@allskills = s.allskills.split("-")
			@allskills.reject!{|element| element.empty?} 
			@allskills.shift 
		end

		puts @allskills.class
		puts @allskills.inspect


		render :partial => 'personsearchresult.html.erb'	
	end

	def peopleSkillViewSearch
		@group = Group.find(params[:id])
		@person = @group.people.all
		render :partial => 'personskillviewsearchresult.html.erb'	
	end
	
	
	def ppledit
		@grp = Group.all
		@person = Person.find(params[:pplid])
		@@pr1 = @person
		render :file => "app/views/person/ppleditview.html.erb"
	end

	def pplupdate
		@@pr1.group_id = params[:grpsel]		
		@@pr1.name = params[:pplname]
		@@pr1.phnum = params[:pplph]
		@@pr1.dob = params[:ppldob]
		@@pr1.fname = params[:pplfname]
		@@pr1.place = params[:pplplace]
		@@pr1.email = params[:pplemail]
		begin 
			file_upload = params[:pplfile]
			@@pr1.propic = file_upload.read
			@@pr1.save
		rescue
			puts 'error'
		end
		flash[:notice] = 'Person Successfully Updated'
		@prsn = Person.order("id").page(params[:page]).per(2)
		render :file => 'app/views/person/personallshow.html.erb'
	end
	def ppldestroy
			@usr = Person.find(params[:id])
			if(@usr.destroy)
				flash[:notice] = 'Person Successfully Deleted'
				redirect_to :action => "personallshow"
			end
	end
	before_filter :set_search#, :only => :allorgshow

	def set_search
		@search=Person.search(params[:q])
	end
	

	def personallshow
		@q = Person.search(params[:q])
    	@prsn = @q.result.order("id").page(params[:page]).per(4)
		#@prsn = Person.all
		render :file => 'app/views/person/personallshow.html.erb'	
	end


	def peopleDisplayByPageRange
		@prsn = Person.order("name").page(params[:page]).per(params[:id])
		render :partial => 'peopleDisplayByPageRange.html.erb'	
	end
	

end

app/helpers/person_helper.rb
module PersonHelper
end

app/views/person/_peopleDisplayByPageRange.html.erb
<table class='table table-striped table-hover' >
			<tr>
				<th> Group Id: </th>
				<th> Person Id </th>
				<th> Name:</th>
				<th> DOB</th>
				<th> Communication Details</th>	
				<th> Picture </th>
				<th colspan='2' class='opth'>Action</th>
			</tr>

		<% @prsn.each do |s| %>
			<tr>
				<td> <%= s.group_id %>
				<td> <%= s.id %> </td>
				<td> <%= s.fname %> <%= s.name %> </td>
				<td> <%= s.dob %> </td>
				<td> <%= s.email %> <br /> <%= s.phnum %> </td>
				<td class='imgstyle'> <% @cont = Base64.encode64(s.propic) %> <img src="data:image/jpeg;base64,<%= @cont %>" class="img-polaroid" />
				<td class='optd' id = 'optd1'> <a href='/ppledit/<%= s.id %>' title='Click to Edit the Organization' name='edit' > <img src='assets/tab_edit.png'> </a> </td>
				<td class='optd1' id=<%= s.name %>> <%= link_to image_tag('/assets/delete.png', :class=>s.id, :id=>'opdelete'), grpdestroy_path(), :title => 'Click to Delete the Organization', :class=> s.id, :id=> 'opdelete' %> </td>
			</tr>
			<% end %>
		</table>

app/views/person/_personsearchresult.html.erb
<html>
<head>
	<script>
			
	</script>
</head>
<body>
<select name ='prsnid' class='span2' id='personfind' %>
<option value='s'> Select Person </option>
		<% @person.each do |p| %>
		<option value =<%= p.id %>   > <%= p.fname %> </option>
		<% end %>
</select>



<br />
<br />
<div>
					Skills:
					<div  id='check1' >
						<% begin %>
		<% @s = @allskills %>
		<% @s.each do |s| %>
			<%= check_box_tag "skills[]",s, false, :id => s %> <%= s.gsub("\|2",'') %>
	  	<% end %>
<% rescue %>
<% end %>
					</div>
				</div>
</body>
</html>

app/views/person/personallshow.html.erb
<html>
	<head>
	
		  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
		  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
		  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
		  <script>
				$('document').ready(function(){
				
				$('.optd1 img').click(function(e){
						
					e.preventDefault();
					var va = $(this).attr("class");
					$( "#dialog-confirm" ).dialog({
					  resizable: false,
					  height:180,
					  width:400,
					  modal: true,
					  buttons: {
						"Delete": function() {
						  $( this ).dialog( "close" );
							//return true;
							  $.ajax({
				        		url: "/ppldestroy",
								data: {id: va},
				        		success: function (data) {
								$("#myid").html("successfully deleted");
								$("#myid1").html("");
				        		}
				    		   });

						 },
						"No": function() {
						  $( this ).dialog( "close" );
							return false;
						  }
						  }
					  }); 
				});				
						
			$('#pagepershow').change(function() { 
						var selectedPageRange = $(this).val()
						if((selectedPageRange == 'null')||(selectedPageRange == ''))			
						{
						}
						else
						{
							$.ajax({
								url:'/peopleDisplayByPageRange',
								data: {id:selectedPageRange},
								dataType: 'html',
								success: function(data) {
									$('#peopleDisplayByPageRange').html(data)
								},
								error: function(data) {
									alert('error Occurred')
								}
							});
						}
				});


				$('#filtering').change(function() { 
						alert('welcome')
						var filtervalue = $(this).val();
							switch(filtervalue) {
								case 'gid':
										$('#groupid').css('visibility', 'visible');
										break;
								case 'pid':
										$('#personid').css('visibility', 'visible');
										break;
								case 'pname':
										$('#personname').css('visibility', 'visible');
										break;
								case 'dob':
										$('#persondob').css('visibility', 'visible');
										break;
								case 'communication':
										$('#personcommnaddress').css('visibility', 'visible');
										break;
								default :
										$('#emptycolumn').css('visibility', 'visible');
										break;
							}
				});
				


});
		  </script>
  <style>
		
	</style>


	</head>
	<body>
		
		<div id='myid1'>
		 <% if flash[:notice] %>
		    <div class="alert alert-success">  
  					<a class="close" data-dismiss="alert">&times;</a>  
					  <strong>Success!</strong> <%= flash[:notice] %>
			</div>  
		 <% end %>
			<br />
<div class='btn pull-right'> <%= link_to 'Create Person',  pplcreate_path %> </div> <br /> <br />



		

		<div id='peopleDisplayByPageRange'>
			<%= search_form_for @search, :url=>'pplallshow' do |f| %>
				  <div class="field">
					<%= f.text_field :fname_or_name_or_id_eq, :placeholder => 'Total Filter', :class=>'filterbox'  %>
				  	<%= f.submit 'Filter', :class=>'btn btn-primary filterbutton' %>
				  </div>
			<% end %>
				
		<table class='table table-striped table-hover' >	
			<%= search_form_for @search, :url=>'pplallshow' do |f| %>
			<tr>
				<td id='ersonname' class='span1'>  <%= f.text_field :fname_or_name_cont, :placeholder => 'Filter', :class=>'filterbox' %> </td>
				<td id='ersondob' class='span1'> <%= f.text_field :dob_eq, :placeholder => 'Filter', :class=>'filterbox' %> </td>
		
		<td id='ersoncommnaddress' class='span2'> <%= f.text_field :email_cont, :placeholder => 'Filter', :class=>'filterbox'  %>  </td>

		<td id='ersoncommnaddress' class='span2'> <%= f.text_field :phnum_eq, :placeholder => 'Filter', :class=>'filterbox'  %>  </td>
			<td id='mptycolumn' colspan='3'> <%= f.submit 'Filter', :class=>'btn btn-primary' %> </td>
			</tr>	
			<% end %>	
			<tr>
				<th> <%= sort_link(@search, :fname, "Name:") %></th>
				<th> <%= sort_link(@search, :dob, "DOB:") %></th>
				<th> <%= sort_link(@search, :email, "Email Id:") %> </th>	
				<th> <%= sort_link(@search, :phnum, "Phone Number:") %> </th>
				<th> Picture </th>
				<th colspan='2' class='opth'>Action</th>
			</tr>

		<% @prsn.each do |s| %>
			<tr>
				<td> <%= s.fname %> <%= s.name %>  </td>
				<td> <%= s.dob %> </td>
				<td> <%= s.email %> </td> 
				<td> <%= s.phnum %> </td>
				<td class='imgstyle'> <% @cont = Base64.encode64(s.propic) %> <img src="data:image/jpeg;base64,<%= @cont %>" class="img-polaroid" />
				
				<td class='optd' id = 'optd1'> <a href='/ppledit/<%= s.id %>' title='Click to Edit the Organization' name='edit' > <img src='assets/tab_edit.png'> </a> </td>
				<td class='optd1' id=<%= s.name %>> <%= link_to image_tag('/assets/delete.png', :class=>s.id, :id=>'opdelete'), grpdestroy_path(), :title => 'Click to Delete the Organization', :class=> s.id, :id=> 'opdelete' %> </td>
			</tr>
			<% end %>
		
		</table>
		</div>
	</div>
    <span class='paginationbg'> <%= paginate @prsn, :window => 2 %> </span>
<br />
<div id="dialog-confirm" title="Do you wanna Delete this?">
  <p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>This item will be permanently deleted and cannot be recovered. Are you sure?</p> </div>

	</body>
</html>

app/views/person/pplcreate.html.erb
<html>
	<head>
		<style>
			.control-label{
				float:left !important;
			}
			.span3 {
				position:absolute;
				right:400px;
			}
		</style>
		<script type='text/javascript'>
				function validateMe() {
						if(validateFName()) {
							if(validateLName()) {
							 	return true; 	
								}
						}
						return false;								
					}

					function validateFName() {
						nameval = document.getElementById('pplfname')
					namevalue = nameval.value
					if((namevalue == 'null') || (namevalue == ''))
						{
							document.getElementById('errormsg1').innerHTML = 'Please Fill the Name'
							nameval.focus();
								return false;
						}
						else {
							document.getElementById('errormsg1').innerHTML = ''
							return true;
						}
					}
					
					function validateLName() {
						nameval = document.getElementById('pplname')
					namevalue = nameval.value
					if((namevalue == 'null') || (namevalue == ''))
						{
							document.getElementById('errormsg2').innerHTML = 'Please Fill the Name'
							nameval.focus()
								return false;
						}
						else {
							document.getElementById('errormsg1').innerHTML = ''
							return true;
						}
					}						
		</script>
		<script>
				$(document).ready(function() { 

						$('#organizationselect').change(function() { 
							var idval = $(this).val();
							$.ajax({
								url:'/groupsearch',
								data: {id:idval},
								dataType:"html",
								success: function(data) { 
									$('.groupsearch').html(data)
								},
								error: function(data) {
									alert('error Occurred')
								}
							});
						});	
				});
		</script>
	</head>
	<body>
		<div class="container"> <div class='btn'>	<%= link_to 'View Person', pplshow_path %> </div> <br /> <br />
			<div class="span12">
				<%= form_tag({:action => "pplsave" }, :multipart=> true, :id => "form_id", :name => 'person', :class => 'form-horizontal', :onsubmit => 'return validateMe()')  do %>
				<div class="control-group">
					<label class="control-label" for="inputId">Organization :</label>
					<div class="controls ">
							<select name='orgsel' class='span2' id='organizationselect'>
								<option value=''> Select Organization </option>
									<% @organization.each do |o| %>
								<option value=<%= o.id %>> <%= o.name %> </option>
									<% end %>
							</select>
					  </div>
			    </div>
				<div class="control-group">
					<label class="control-label" for="inputId">Group :</label>
					<div class="controls groupsearch">
							<select name='grpsel' class='span2' disabled='disabled'>
								<option value=''> </option>
							</select>
					  </div>
			    </div>
				<div class="control-group">
					<label class="control-label" for="inputName">First Name:</label>
					<div class="controls">
					  <input type="text" name ='pplfname' id="pplfname" placeholder="First Name" onblur='return validateFName()'> <span id='errormsg1'> </span>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputLName">Last Name:</label>
					<div class="controls">
					  <input type="text" name ='pplname' id="pplname" placeholder="Last Name" onblur='return validateLName()'> <span id='errormsg2'> </span>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputProfilePicture">Profile Picture</label>
					<div class="controls">
					  <input type="file" name ='pplfile' id="pplfile" placeholder="Place">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputcity">Place</label>
					<div class="controls">
					  <input type="text" name ='pplplace' id="pplplace" placeholder="Place">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputDob">Dob</label>
					<div class="controls">
					  <input type="text" name ='ppldob' id="ppldob" placeholder="DD-MM-YYYY">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputphone">Phone Number</label>
					<div class="controls">
					  <input type="text" name ='pplph' id="pplph" placeholder="Phone Number">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputEmail">Email</label>
					<div class="controls">
					  <input type="text" name ='pplemail' id="pplemail" placeholder="Email">
					</div>
				</div>
				
			<div class="pull-left span3">
				<%= submit_tag "Save", :id => "uploadid", :class => 'btn btn-primary'%>
			</div>
	<% end %>
	<br />

 	</body>
</html>

app/views/person/ppldisplay.html.erb
<html>
	<head>
		  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
		  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
		  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
		  <script>
				$('document').ready(function(){
				
				$('#opdelete').click(function(e){
						
					e.preventDefault();
					var va = $(this).attr("class");
					$( "#dialog-confirm" ).dialog({
					  resizable: false,
					  height:180,
					  width:400,
					  modal: true,
					  buttons: {
						"Delete": function() {
						  $( this ).dialog( "close" );
							//return true;
							  $.ajax({
				        		url: "/ppldestroy",
								data: {id: va},
				        		success: function (data) {
								 $("#myid").html("successfully deleted");
								 $('#myid1').html("");
				        		}
				    		   });

						 },
						"No": function() {
						  $( this ).dialog( "close" );
							return false;
						  }
						  }
					  }); 
				});				
						

});
		  </script>
		
			<style>
				table{
					width:500px !important;
				}				
				td,th{
					width:100px !important;
				}
			</style>
	</head>
	<body>
	<div id="myid1">

		<div class='pull-right'>
			<%= link_to 'Add Person', pplcreate_path, :class=> 'btn'%>
		</div>
		<h1>Person Information</h1>

<table class='table table-stiped table-hover profilepic'>
  <tr>
    <th>User Id</th> <td><%= @person.id%></td> <% @cont = Base64.encode64(@person.propic) %>
    <td rowspan='3' class='imgstyle'> <img src="data:image/jpeg;base64,<%= @cont %>" class="img-polaroid" /> </td>
  </tr>
  <tr>
    <th>User First Name</th> <td> <%=@person.fname %> </td> 
  </tr>
  <tr> 
    <th>User Last Name</th> <td><%= @person.name %></td> 
  </tr>
  <tr>
    <th>User Date of Birth</th> <td><%= @person.dob %></td> <td> </td>
  </tr>
  <tr>
    <th>User Email id</th> <td> <%= @person.email %> </td> <td> </td>
  </tr>
  <tr> 
    <th>User Place</th> <td><%= @person.place %></td> <td> </td>
  </tr>
  <tr>
    <th>User Phone Number</th> <td> <%= @person.phnum %> </td> <td> </td>
  </tr>
  <tr>
	<% begin %>
    <th> Skills </th> <td> <% @allskills.each do |s| %>
    	<%= sanitize(s.to_s.gsub('"',"").gsub('\r',"").gsub('\n',"<br/>")) %>
	<% end %>	</td> <td> </td>
	<% rescue %>
	<% end %>
  </tr>
  <tr> <th> Action </th>

	<td id='op1'> <a href='/ppledit/<%= @person.id %>' title='Click to Edit the User' id='opedit' > <img src='assets/tab_edit.png'> </a> &nbsp; &nbsp; &nbsp; &nbsp;	<%= link_to image_tag('/assets/delete.png'), ppldestroy_path(:id=>@person.id), :title=>'Click to Delete the User', :class=> @person.id, :id=> 'opdelete' %> </td> <td> </td>
  </tr>
 </table>
</div>
<br />

<div id="dialog-confirm" title="Do you wanna Delete this?">
  <p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>This item will be permanently deleted and cannot be recovered. Are you sure?</p> </div>

	<div class='btn'> <%= link_to 'show', pplshow_path %> </div>
	</body>
</html>

app/views/person/ppleditview.html.erb
<html>
	<head>
		<style>
			.control-label{
				float:left !important;
			}
			.span3 {
				position:absolute;
				right:400px;
			}
		</style>
		<script type='text/javascript'>
				function validateMe() {
						if(validateFName()) {
							if(validateLName()) {
							 	return true; 	
								}
						}
						return false;								
					}

					function validateFName() {
						nameval = document.getElementById('pplfname')
					namevalue = nameval.value
					if((namevalue == 'null') || (namevalue == ''))
						{
							document.getElementById('errormsg1').innerHTML = 'Please Fill the Name'
							nameval.focus();
								return false;
						}
						else {
							document.getElementById('errormsg1').innerHTML = ''
							return true;
						}
					}
					
					function validateLName() {
						nameval = document.getElementById('pplname')
					namevalue = nameval.value
					if((namevalue == 'null') || (namevalue == ''))
						{
							document.getElementById('errormsg2').innerHTML = 'Please Fill the Name'
							nameval.focus()
								return false;
						}
						else {
							document.getElementById('errormsg1').innerHTML = ''
							return true;
						}
					}						
		</script>
	</head>
	<body>
		<div class="container">
			<div class="span12">
				<%= form_tag({:action => "pplupdate" }, :multipart=> true, :id => "form_id", :name => 'person', :class => 'form-horizontal', :onsubmit => 'return validateMe()')  do %>
				<div class="control-group">
					<label class="control-label" for="inputId">Group Name:</label>
					<div class="controls">
							<select name='grpsel' class='span2'>
									<% @grp.each do |g| %>
								<option value=<%= g.id %>> org: <%= g.organization_id %> grp: <%= g.id %> <%= g.name %> </option>
									<% end %>
							</select>
					  </div>
			    </div>
				<div class="control-group">
					<label class="control-label" for="inputName">First Name:</label>
					<div class="controls">
					  <input type="text" name ='pplfname' id="pplfname" value=<%= @person.fname %> onblur='return validateFName()'> <span id='errormsg1'> </span>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputLName">Last Name:</label>
					<div class="controls">
					  <input type="text" name ='pplname' id="pplname" value=<%= @person.name %> onblur='return validateLName()'> <span id='errormsg2'> </span>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputProfilePicture">Profile Picture</label>
					<div class="controls">
					  <input type="file" name ='pplfile' id="pplfile" value=<%= @person.propic %>>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputcity">Place</label>
					<div class="controls">
					  <input type="text" name ='pplplace' id="pplplace" value=<%= @person.place %>>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputDob">Dob</label>
					<div class="controls">
					  <input type="text" name ='ppldob' id="ppldob" value=<%= @person.dob %>>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputphone">Phone Number</label>
					<div class="controls">
					  <input type="text" name ='pplph' id="pplph" value=<%= @person.phnum %>>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputEmail">Email</label>
					<div class="controls">
					  <input type="text" name ='pplemail' id="pplemail" value=<%= @person.email %>>
					</div>
				</div>
				
			<div class="pull-left span3">
				<%= submit_tag "Update", :id => "uploadid", :class => 'btn btn-primary'%>
			</div>
	<% end %>
	<br />
		<%= link_to 'Back', pplshow_path %>
 	</body>
</html>

app/views/person/remsuccess.html.erb
<h1> Success fully Removed </h1>

<br />	
	<%= link_to 'Create New', pplcreate_path %>

app/views/person/success.html.erb
<h1> Success fully Created </h1>

<br />	
	<%= link_to 'Create New', pplcreate_path %>

app/views/person/upsuccess.html.erb
<h1> Updated Successfully.... </h1>


<br />	
	<%= link_to 'Create New', pplcreate_path %>