config/routes.rb
Skillmanagementsystem::Application.routes.draw do
	match 'ocreate', :controller => 'organization', :action => 'orgcreate'
	match 'orgsave', :controller => 'organization', :action => 'orgsave'
	match 'oview', :controller => 'organization', :action => 'view'
	match 'oviewgrp', :controller => 'organization', :action => 'viewgrp'
	match 'show', :controller => 'organization', :action => 'show'
	match 'allorgshow', :controller => 'organization', :action => 'allorgshow'
	match 'orgdestroy', :controller => 'organization', :action => 'orgdestroy'
	match 'orgedit/:oid', :controller => 'organization', :action => 'orgedit'
	match 'orgupdate', :controller => 'organization', :action => 'orgupdate'
	match 'pageper', :controller => 'organization', :action => 'pageper'
	match 'grpshow', :controller => 'organization', :action => 'grpshow'
	
	match 'gcreate', :controller => 'group', :action => 'grpcreate'
	match 'grpsave', :controller => 'group', :action => 'grpsave'
	match 'search', :controller => 'group', :action => 'search'
	match 'groupshow', :controller => 'group', :action => 'groupshow'
	match 'grpdestroy', :controller => 'group', :action => 'grpdestroy'
	match 'grpedit/:grpid', :controller => 'group', :action => 'grpedit'
	match 'grpupdate', :controller => 'group', :action => 'grpupdate'
	match 'grpallshow', :controller => 'group', :action => 'groupallshow'
	match 'groupsearch', :controller => 'group', :action => 'groupsearch'
	match 'groupskillsearch', :controller => 'group', :action => 'groupskillsearch'
	match 'groupDisplayRange', :controller => 'group', :action => 'groupDisplayRange'
	match 'groupSkillSearch', :controller => 'group', :action => 'groupSkillSearch'

	match 'pplcreate', :controller => 'person', :action => 'pplcreate'
	match 'pplsave', :controller => 'person', :action => 'pplsave'
	match 'pplshow', :controller => 'person', :action => 'pplshow'
	match 'ppldisplay', :controller => 'person', :action => 'ppldisplay'
	match 'ppldisplay/:prsnid', :controller => 'person', :action => 'ppldisplay'
	match 'ppldestroy', :controller => 'person', :action => 'ppldestroy'
	match 'ppledit/:pplid', :controller => 'person', :action => 'ppledit'
	match 'pplupdate', :controller => 'person', :action => 'pplupdate'
	match 'pplallshow', :controller => 'person', :action => 'personallshow'
	match 'peoplesearch', :controller => 'person', :action => 'peoplesearch'
	match 'peopleskillsearch', :controller => 'person', :action => 'peopleskillsearch'
	match 'peopleDisplayByPageRange', :controller => 'person', :action => 'peopleDisplayByPageRange'
	match 'peopleSkillViewSearch', :controller => 'person', :action => 'peopleSkillViewSearch'

	match 'spsave', :controller => 'skill', :action => 'spsave'
	match 'spshow', :controller => 'skill', :action => 'spshow'
	match 'sgcreate', :controller => 'skill', :action => 'sgcreate'
	match 'sgsave', :controller => 'skill', :action => 'sgsave'
	match 'sgshow', :controller => 'skill', :action => 'sgshow'
	match 'sgdisplay', :controller => 'skill', :action => 'sgdisplay'
	match 'spcreate', :controller => 'skill', :action => 'spcreate'
	match 'spdisplay', :controller => 'skill', :action => 'spdisplay'
	match 'skilldestroy', :controller => 'skill', :action => 'skilldestroy'
	match 'usrskilledit/:sid&:gid&:pid', :controller => 'skill', :action => 'usrskilledit'
	match 'usrskillupdate', :controller => 'skill', :action => 'usrskillupdate'
	match 'grpskilledit/:sid&:gid', :controller => 'skill', :action => 'grpskilledit'
	match 'groupskilledit/:sid&:gid', :controller => 'skill', :action => 'groupskilledit'
	match 'grpskillupdate', :controller => 'skill', :action => 'grpskillupdate'
	match 'skillsearch', :controller => 'skill', :action => 'skillsearch'	
	match 'skillviewsearch', :controller => 'skill', :action => 'skillviewsearch'
	match 'allGroupSkills', :controller => 'skill', :action => 'allGroupSkills'
	match 'allPersonSkills', :controller => 'skill', :action => 'allPersonSkills'

	match 'showAllSkills', :controller => 'skill', :action => 'showAllSkills'
	

   root :to => 'organization#index'

end

app/models/organization.rb
class Organization < ActiveRecord::Base

  attr_accessible :name, :email, :city, :state, :website, :phnum
	has_many :groups, :dependent => :destroy
	has_many :people, :dependent => :destroy
	
end

app/controllers/organization_controller.rb
class OrganizationController < ApplicationController
	def index 
		org = Organization.all
		grp = Group.all
		prsn = Person.all
		@org = org.count
		@grp = grp.count
		@prsn = prsn.count
		render :file => "app/views/organization/oindex.html.erb"
	end

	
	def show
		@org = Organization.find(params[:orgsel])
		@q = @org.people.search(params[:q])
    	@data = @q.result.order("id").page(params[:page]).per(4)
	end
	
	def grpshow
		@org = Organization.find(params[:orgsel])
		@q = @org.groups.search(params[:q])
    	@grp = @q.result.order("id").page(params[:page]).per(3)
		render :file => 'app/views/organization/grpshow.html.erb'	
	end
	
	def view
		@org = Organization.all
		render :file => 'app/views/organization/oview.html.erb'
	end
	
	def viewgrp
		@org = Organization.all
		render :file => 'app/views/organization/grpview.html.erb'
	end	

	def orgcreate
		render :file => "app/views/organization/ocreate.html.erb"
	end

	def orgsave
		@organization = Organization.create(params[:organization])
		if @organization
			flash[:notice] = "Organization Successfully Created"
			redirect_to :action => "allorgshow"
		end	
	end

	before_filter :set_search#, :only => :allorgshow

	def set_search
		@search2 = Person.search(params[:q])
    	@search1 = Group.search(params[:q])
		@search=Organization.search(params[:q])
	end

	
	def allorgshow
        
		@q = Organization.search(params[:q])
    	@organization = @q.result.order("id").page(params[:page]).per(2)
			
		#@organization = Organization.order("name").page(params[:page]).per(2)
		render :file => "app/views/organization/orgallshow.html.erb"
	end
	
	def pageper
		@org = Organization.order("name").page(params[:page]).per(params[:id])
		render :partial => "pagepershow.html.erb"
	end

	def orgedit
		@org = Organization.find(params[:oid])	
		@@or1 = @org
		render :file => "app/views/organization/oeditview.html.erb"
	end

	def orgupdate
		@@or1.name = params[:orgname]
		@@or1.city = params[:orgcity]
		@@or1.state = params[:orgstate]
		@@or1.phnum = params[:orgph]
		@@or1.email = params[:orgemail]
		@@or1.website = params[:orgweb]
		if(@@or1.save) 
			flash[:notice] = "Organization Successfully Updated"
			redirect_to :action => "allorgshow"	
		end
	end

	def orgdestroy
		@org = Organization.find(params[:id])
		if(@org.destroy)
		flash[:notice] = 'Organization Successfully Deleted'
		redirect_to :action => "allorgshow"
		end		
	end
end

app/helpers/organization_helper.rb
module OrganizationHelper
end

app/views/organization/_pagepergroupshow.html.erb
<table class='table table-striped table-hover'>
			<tr>
				<th> Organization Id </th>
				<th> Organization Name </th>
				<th> Group Id </th> 
				<th> Group Name </th>
				<th class='opth' colspan='2'> Action </th>
			</tr>

		<% @grp.each do |s| %>
			<tr>
				<td> <%= @org.id %> </td>
				<td> <%= @org.name %> </td>
				<td> <%= s.id %> </td>
				<td> <%= s.name %> </td>
				<td class='optd'> <a href='/grpedit/<%= s.id %>' title='Click to Edit the Group' > <img src='assets/tab_edit.png'> </a> </td>
				<td class='optd1' id=<%= s.name %>> <%= link_to image_tag('/assets/delete.png', :class=> s.id, :id=> 'opdelete'),grpdestroy_path(:id => s.id), :title=>'Click to Delete the Group' %>  </td>
		</tr>
		<% end %>
		</table>

app/views/organization/_pagepershow.html.erb
<table class="table table-striped table-hover">
			<tr>
				<th> Organization Id: </th>
				<th> Name:</th>
				<th> Address </th>
				<th> Communication Address </th>
				<th colspan='2' class='opth'>Action</th>
			</tr>

		<% @org.each do |s| %>
			<tr>
				<td> <%= s.id %> </td>
				<td> <%= s.name %> </td>
				<td> <%= s.city %> <br /> <%= s.state %>  </td>
				<td> <%= s.email %> <br/> <%= s.website %> <br /> <%= s.phnum %> </td>
				<td class='optd' id = 'optd1'> <a href='/orgedit/<%= s.id %>' title='Click to Edit the Organization' name='edit' > <img src='assets/tab_edit.png'> </a> </td>
				<td class='optd1' id=<%= s.name %>> <%= link_to image_tag('/assets/delete.png', :class=>s.id, :id=>'opdelete'), orgdestroy_path(), :title => 'Click to Delete the Organization', :class=> s.id, :id=> 'opdelete' %> </td>
			</tr>
			<% end %>
		</table>

app/views/organization/grpshow.html.erb
<html>
	<head>
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
		  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
		  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
		  <script>
				$('document').ready(function(){
					
				$('.optd1 img').click(function(e){
						
					e.preventDefault();
					var va = $(this).attr("class");
					$( "#dialog-confirm" ).dialog({
					  resizable: false,
					  height:180,
					  width:400,
					  modal: true,
					  buttons: {
						"Delete": function() {
						  $( this ).dialog( "close" );
							//return true;
							  $.ajax({
				        		url: "/grpdestroy",
								data: {id: va},
				        		success: function (data) {
								$("#myid").html("successfully deleted");
								$('#myid1').html("");
				        		}
				    		   });

						 },
						"No": function() {
						  $( this ).dialog( "close" );
							return false;
						  }
						  }
					  }); 
				});	


				$('#pagepershow').change(function() { 
						var selectedPageRange = $(this).val()
						if((selectedPageRange == 'null')||(selectedPageRange == ''))			
						{
						}
						else
						{
							$.ajax({
								url:'/groupShowSelected',
								data: {id:selectedPageRange},
								dataType: 'html',
								success: function(data) {
									$('#partialtable').html(data)
								},
								error: function(data) {
									alert('error Occurred')
								}
							});
						}
				});





			
						

});
		  </script>
	</head>
	<body>







		<div id='myid1'>

		<div class='pull-right'> 
				<%= link_to 'Add Group', gcreate_path, :class=>'btn'  %>
		</div>

        <%= search_form_for @search1, :url=>'grpshow'  do |f| %>
				 <div class="field">
					<%= f.hidden_field :organization_id_eq, :value => @org.id , :name => 'orgsel' %>
					 <%= f.text_field :organization_name_or_name_cont, :placeholder => 'Total Filter', :class=>'filterbox'  %>
	 			  	 <%= f.submit 'Filter', :class=>'btn btn-primary filterbutton' %>
				  </div>
		<% end %>
	
	<div id ='partialtable'>
		<table class='table table-striped table-hover'>
			<%= search_form_for @search1, :url=>'grpshow'  do |f| %>
			<tr>
				<%= f.hidden_field :organization_id_eq, :value => @org.id , :name => 'orgsel' %>
				<td> <%= f.text_field :organization_name_cont, :placeholder => 'Filter', :class=>'filterbox' %> </td>
				<td id='gname'> <%= f.text_field :name_cont, :placeholder => 'Filter', :class=>'filterbox' %> </td>
				<td id='mptycolumn' colspan='2'> <%= f.submit 'Filter', :class=>'btn btn-primary' %> </td>
			</tr>	
		  <% end %>	
			<tr>
				<th> <%= sort_link(@search, :organization_name, "Organization Name:", {action: 'grpshow', orgsel: @org.id} ) %>  </th>
				<th> <%= sort_link(@search, :name, "Group Name:", {action: 'grpshow', orgsel: @org.id} ) %>  </th>
				<th class='opth' colspan='2'> Action </th>
			</tr>

		<% @grp.each do |s| %>
			<tr>
				<td> <%= @org.name %> </td>
				<td> <%= s.name %> </td>
				<td class='optd'> <a href='/grpedit/<%= s.id %>' title='Click to Edit the Group' > <img src='assets/tab_edit.png'> </a> </td>
				<td class='optd1' id=<%= s.name %>> <%= link_to image_tag('/assets/delete.png', :class=> s.id, :id=> 'opdelete'),grpdestroy_path(:id => s.id), :title=>'Click to Delete the Group' %>  </td>
		</tr>
		<% end %>
		</table>
	</div>
	</div>
	<%= paginate @grp %>
<br />

<div id="dialog-confirm" title="Do you wanna Delete this?">
  <p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>This item will be permanently deleted and cannot be recovered. Are you sure?</p> </div>


<div class='btn'> <%= link_to 'Back', oviewgrp_path %> </div>

	</body>
</html>

app/views/organization/grpview.html.erb
<%= form_tag({:action => 'grpshow'}, :class=>'form-horizontal') do %>
Choose Organization: <select name='orgsel'>
			<% @org.each do |o| %>
			<option value=<%= o.id %>> <%= o.name %> </option>
			<% end %>
		</select>
<%= submit_tag "Show", :id => "uploadid", :class => 'btn btn-primary'%>
<% end %>

<div class='btn'> <%= link_to 'Show Users', oview_path %> </div>

app/views/organization/oindex.html.erb
<html>
	<title> Skill Management System </title>
	<head>
		<style>
			.menuitems {
				padding:10px;
			}
			.heading {
				border-radius:50px;
				background: #DDDDDD;
				text-align: left;
				padding:0px;
				margin:2px 0px 0px 0px;
			}
			h4 {
				margin-left:20px;
			}			
			.menucontainer {
				background:#EEEEEE;
				border-radius:10px;
				box-shadow:8px 5px 5px #000;
			}
			.lastone {
				margin-bottom:30px !important;
			}
			.bgimg {
				background:#f2f2f2;
				border-radius:10px;
				box-shadow:2px 3px 4px #ddd;
				width:80px;
				padding-left:10px;
				margin-right:20px;
			}
			.menu {
				width:500px !important;
			}
			
		</style>
		<script>
			$(document).ready(function() { 

				$('#orgcreate').tooltip({
					title: 'Click to Goto the Organization Creation Form',
					placement: 'bottom'

				})
			
				$('#grpcreate').tooltip({
					title: 'Click to Goto the Group Creation Form',
					placement: 'bottom'

				})

				$('#pplcreate').tooltip({
					title: 'Click to Goto the User Creation Form',
					placement: 'bottom'

				})

				$('#orgview1').tooltip({
					title: 'Displaying all Organizations',
					placement: 'bottom'

				})
			
				$('#grpview1').tooltip({
					title: 'Showing you to the Groups',
					placement: 'bottom'

				})

				$('#pplview').tooltip({
					title: 'Getting all the Person Details',
					placement: 'bottom'

				})

				$('#skillcreate1').tooltip({
					title: 'Creating Skills for Person',
					placement: 'bottom'

				})

				$('#skillview').tooltip({
					title: 'Retrieving Skills of Group',
					placement: 'bottom'

				})

				$('#grpskillcreate').tooltip({
					title: 'Creating Skills for Group',
					placement: 'bottom'

				})
		
			});
		</script>
	</head>
	<body>
		<div class='containter'>
			<div class='row well'>
				 You can view all Persons, Organizations, Groups  Directly when you click on number
			</div>
			<div class='row'>
			  <div class='span12'> <!-- Main div Opened -->
			  <div class='span5 menucontainer pull-left'> <!-- Menu Item -->
				<div class='span5 heading'>
					<h4> Dashboard </h4>
				</div>
				<div class='span5'>
					<div class='span3 menuitems'> <img src='assets/home.png' /> Organizations </div>
					<div class = 'span1 menuitems'> <%= link_to @org, allorgshow_path, :title=>'Show Organizations' %> </div>
					<div class='span3 menuitems'> <img src='assets/group1.png' /> Groups </div>
					<div class = 'span1 menuitems'> <%= link_to @grp, grpallshow_path, :title=>'Show Groups' %> </div>
					<div class='span3 menuitems'> <img src='assets/user1.png' /> Persons </div>
					<div class = 'span1 menuitems'> <%= link_to @prsn, pplallshow_path, :title=>'Show Users' %> </div>
				</div>
			  </div> <!-- Menu Items Closed -->
			  <div class='span6 pull-right menu'>
					<div class='span2 bgimg'> <%= link_to image_tag('/assets/company.png', :id=>'orgcreate'), ocreate_path %> <small> <center> creat Org </center> </small> </div>
					<div class='span2 bgimg'>  <%= link_to image_tag('/assets/user-group.png',  :id=>'grpcreate'), gcreate_path %> <small> <center> creat group </center> </small> </div> 
					<div class='span1 lastone bgimg'> <%= link_to image_tag('/assets/people.png', :id=>'pplcreate'), pplcreate_path %>  <small> <center> creat user </center> </small> </div>
	
					<!-- Viewing -->
	
					<div class='span2 imgsize bgimg'> <%= link_to image_tag('/assets/gwenview.png', :id=>'orgview1'), allorgshow_path %> <small> <center> show org </center> </small> </div>
					<div class='span2 imgsize bgimg'>  <%= link_to image_tag('/assets/kuser.png',  :id=>'grpview1'), grpallshow_path %> <small> <center> show group </center> </small> </div>
					<div class='span1 lastone bgimg'> <%= link_to image_tag('/assets/administrator.png', :id=>'pplview'), pplallshow_path %> <small> <center> show user </center> </small> </div>


					<div class='span2 bgimg'> <%= link_to image_tag('/assets/skills.png', :id=>'skillcreate1'), spcreate_path %> <small> <center> creat person skill </center> </small> </div>
					<div class='span2 bgimg'>  <%= link_to image_tag('/assets/view.png', :id=>'skillview'), sgshow_path %> <small> <center> show group skill </center> </small> </div>
					<div class='span1 lastone bgimg'> <%= link_to image_tag('/assets/skillcreate.png', :id=>'grpskillcreate'), sgcreate_path %> <small> <center> creat group skills </center> </small> </div>

			  </div>
			</div> <!-- Main div closed -->
			</div>
		</div>
	</body>
</html>

app/views/organization/orgallshow.html.erb
<html>
	<title> Skill Management System </title>
	<head>
		  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
		  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
		  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
		  <script>
				$('document').ready(function(){
				
				$('.optd1 img').click(function(e){
						
					e.preventDefault();
					var va = $(this).attr("class");
					$( "#dialog-confirm" ).dialog({
					  resizable: false,
					  height:180,
					  width:400,
					  modal: true,
					  buttons: {
						"Delete": function() {
						  $( this ).dialog( "close" );
							//return true;
							  $.ajax({
				        		url: "/orgdestroy",
								data: {id: va},
				        		success: function (data) {
								$("#myid1").html('');
								$("#myid").html('Successfully Removed');
				        		}
				    		   });
						 },
						"No": function() {
						  $( this ).dialog( "close" );
							return false;
						  }
						  }
					  }); 
				});				
				
				$('#pagepershow').change(function() { 
						var selectedPageRange = $(this).val()
						if((selectedPageRange == 'null')||(selectedPageRange == ''))			
						{
						}
						else
						{
							$.ajax({
								url:'/pageper',
								data: {id:selectedPageRange},
								dataType: 'html',
								success: function(data) {
									$('#partialtable').html(data)
								},
								error: function(data) {
									alert('error Occurred')
								}
							});
						}
				});
					
	});
		  </script>

	<style>
		.inputbox {
			width:100px !important;
		}
		input {
			width:100px !important;
		}
	</style>


	</head>
	<body>
		
		<div id='myid1'>
		 <% if flash[:notice] %>
		    <div class="alert alert-success">  
  					<a class="close" data-dismiss="alert">&times;</a>  
					  <strong>Success!</strong><%= flash[:notice] %>
			</div>  
		 <% end %>
			<br />
		<div class='btn pull-left'> <%= link_to 'Back',  root_path %> </div>  <div class='btn pull-right'> <%= link_to 'Create Organization',  ocreate_path %> </div> <br/>
<br/>



			<%= search_form_for @search, :url=>'allorgshow' do |f| %>
				  <div class="field">
					<%= f.text_field :name_or_email_or_website_or_city_or_state_cont, :placeholder => 'Total Filter', :class=>'filterbox'  %>
				  	<%= f.submit 'Filter', :class=>'btn btn-primary filterbutton' %>
				  </div>
			<% end %>


		<div id='partialtable'>
		<table class="table table-striped table-hover">

			<%= search_form_for @search, :url=>'allorgshow' do |f| %>
			<tr>
				<td id='name'>  <%= f.text_field :name_cont, :placeholder => 'Filter' %> </td>
				<td id='address'> <%= f.text_field :city_or_state_cont, :placeholder => 'Filter' %> </td>
				<td id='commnaddr'> <%= f.text_field :email_or_website_cont, :placeholder=>'Filter' %> </td>
			    <td id='mptycolumn' colspan='2'> <%= f.submit 'Filter', :class=>'btn btn-primary' %> </td>
			</tr>	
			<% end %>	

			<tr>
				<th> <%= sort_link(@search, :name, "Organization Name") %> </th>
				<th> <%= sort_link(@search, :city, "Address:") %>  </th>
				<th> <%= sort_link(@search, :email, "Communication Address:") %>  </th>
				<th colspan='2' class='opth'>Action</th>
			</tr>

		<% @organization.each do |s| %>
			<tr>
				<td> <%= s.name %> </td>
				<td> <%= s.city %> <br /> <%= s.state %>  </td>
				<td> <%= s.email %> <br/> <%= s.website %> <br /> <%= s.phnum %> </td>
				<td class='optd' id = 'optd1'> <a href='/orgedit/<%= s.id %>' title='Click to Edit the Organization' name='edit' > <img src='assets/tab_edit.png'> </a> </td>
				<td class='optd1' id=<%= s.name %>> <%= link_to image_tag('/assets/delete.png', :class=>s.id, :id=>'opdelete'), orgdestroy_path(), :title => 'Click to Delete the Organization', :class=> s.id, :id=> 'opdelete' %> </td>
			</tr>
			<% end %>
			
		</table>
		</div>
	</div>


	<span class='paginationbg'> <%= paginate @organization %> </span>

<br />
<div id="dialog-confirm" title="Do you wanna Delete this?">
  <p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>This item will be permanently deleted and cannot be recovered. Are you sure?</p> </div>
	</body>
</html>

app/views/organization/oview.html.erb
<div class='btn'> <%= link_to 'Create New Organization', ocreate_path %> </div> <br/> <br />

<%= form_tag({:action => 'show'}, :class=>'form-horizontal') do %>
Choose Organization : <select name='orgsel'>
			<% @org.each do |o| %>
			<option value=<%= o.id %>> <%= o.name %> </option>
			<% end %>
		</select>
<%= submit_tag "Show", :id => "uploadid", :class => 'btn btn-primary'%>
<% end %>

app/views/organization/remsuccess.html.erb
<h1> Success fully Removed </h1>

<br/>
<%= link_to 'Create New', ocreate_path%>

app/views/organization/show.html.erb
<html>
	<head>
		  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
		  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
		  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
		  <script>
				$('document').ready(function(){
				
				$('.optd1 img').click(function(e){
						
					e.preventDefault();
					var va = $(this).attr("class");
					$( "#dialog-confirm" ).dialog({
					  resizable: false,
					  height:180,
					  width:400,
					  modal: true,
					  buttons: {
						"Delete": function() {
						  $( this ).dialog( "close" );
							  $.ajax({
				        		url: "/ppldestroy",
								data: {id: va},
				        		success: function (data) {
									$("#myid").html("successfully deleted");
									$("#myid1").html(" ");
				        		}
				    		  });

						 },
						"No": function() {
						  $( this ).dialog( "close" );
						  }
						 }
					  }); 
				});				
						

});
		  </script>
	</head>
	<body>
		<div id='myid1'>
		<div class='pull-right'>
			<%= link_to 'Add Person', pplcreate_path, :class=>'btn' %>
		</div>


		<%= search_form_for @search2, :url=>'show'  do |f| %>
				 <div class="field">
					<%= f.hidden_field :organization_id_eq, :value => @org.id , :name => 'orgsel' %>
					 <%= f.text_field :organization_name_or_fname_cont, :placeholder => 'Total Filter', :class=>'filterbox'  %>
	 			  	 <%= f.submit 'Filter', :class=>'btn btn-primary filterbutton' %>
				  </div>
		<% end %>



		<table class='table table-striped table-hover' >
			<%= search_form_for @search2, :url=>'show'  do |f| %>
			<tr>
				<%= f.hidden_field :organization_id_eq, :value => @org.id , :name => 'orgsel' %>
				<td> <%= f.text_field :organization_name_cont, :placeholder => 'Filter', :class=>'filterbox' %> </td>
				<td id='gname'> <%= f.text_field :fname_cont, :placeholder => 'Filter', :class=>'filterbox' %> </td>
				<td id='gname'> <%= f.text_field :phnum_eq, :placeholder => 'Filter', :class=>'filterbox' %> </td>			
				<td id='mptycolumn' colspan='2'> <%= f.submit 'Filter', :class=>'btn btn-primary' %> </td>
			</tr>	
		  <% end %>	
	




			<tr>
				<th> <%= sort_link(@q, :organization_name, "Organization Name:", {action: 'show', orgsel: @org.id} ) %> </th>
				<th><%= sort_link(@q, :fname, "Person Name:", {action: 'show', orgsel: @org.id} ) %> </th>
				<th><%= sort_link(@q, :phnum, "Phone Number:", {action: 'show', orgsel: @org.id} ) %> </th>
				<th class='opth' colspan='2'> Action </th>

			</tr>

		<% @data.each do |person| %>
			<tr>
				<td> <%= @org.name %> </td>
				<td> <a href='/ppldisplay/<%= person.id %>' title = 'Click to View about Person'> <%= person.fname %>  </a> </td>
				<td> <%= person.phnum %> </td>
				<td class='optd'> <a href='/ppledit/<%= person.id %>' title='Click to Edit the User' > <img src='assets/tab_edit.png'> </a> </td>
				<td class='optd1'> <%= link_to image_tag('/assets/delete.png', :class=>person.id, :id=>'opdelete'), ppldestroy_path(:id => person.id), :title=>'Click to Delete the User', :class=>person.id, :id=>'opdelete' %>  </td>

			</tr>
		<% end %>
		</table>
	<span class='paginationbg'> <%= paginate @data %> </span> 
	</div>


<div id="dialog-confirm" title="Do you wanna Delete this?">
  <p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>This item will be permanently deleted and cannot be recovered. Are you sure?</p> </div>

	<br />
		<div class='btn'> <%= link_to 'Back', oview_path %> </div>
	</body>
</html>

app/views/organization/success.html.erb
<h1> Success fully Created </h1>

<br/>
<%= link_to 'Create New', ocreate_path%>

app/views/organization/upsuccess.html.erb
<h1> Updated Successfully.... </h1>

<br/>
<%= link_to 'Create New', ocreate_path%>