config/routes.rb
Skillmanagementsystem::Application.routes.draw do
	match 'ocreate', :controller => 'organization', :action => 'orgcreate'
	match 'orgsave', :controller => 'organization', :action => 'orgsave'
	match 'oview', :controller => 'organization', :action => 'view'
	match 'oviewgrp', :controller => 'organization', :action => 'viewgrp'
	match 'show', :controller => 'organization', :action => 'show'
	match 'allorgshow', :controller => 'organization', :action => 'allorgshow'
	match 'orgdestroy', :controller => 'organization', :action => 'orgdestroy'
	match 'orgedit/:oid', :controller => 'organization', :action => 'orgedit'
	match 'orgupdate', :controller => 'organization', :action => 'orgupdate'
	match 'pageper', :controller => 'organization', :action => 'pageper'
	match 'grpshow', :controller => 'organization', :action => 'grpshow'
	
	match 'gcreate', :controller => 'group', :action => 'grpcreate'
	match 'grpsave', :controller => 'group', :action => 'grpsave'
	match 'search', :controller => 'group', :action => 'search'
	match 'groupshow', :controller => 'group', :action => 'groupshow'
	match 'grpdestroy', :controller => 'group', :action => 'grpdestroy'
	match 'grpedit/:grpid', :controller => 'group', :action => 'grpedit'
	match 'grpupdate', :controller => 'group', :action => 'grpupdate'
	match 'grpallshow', :controller => 'group', :action => 'groupallshow'
	match 'groupsearch', :controller => 'group', :action => 'groupsearch'
	match 'groupskillsearch', :controller => 'group', :action => 'groupskillsearch'
	match 'groupDisplayRange', :controller => 'group', :action => 'groupDisplayRange'
	match 'groupSkillSearch', :controller => 'group', :action => 'groupSkillSearch'

	match 'pplcreate', :controller => 'person', :action => 'pplcreate'
	match 'pplsave', :controller => 'person', :action => 'pplsave'
	match 'pplshow', :controller => 'person', :action => 'pplshow'
	match 'ppldisplay', :controller => 'person', :action => 'ppldisplay'
	match 'ppldisplay/:prsnid', :controller => 'person', :action => 'ppldisplay'
	match 'ppldestroy', :controller => 'person', :action => 'ppldestroy'
	match 'ppledit/:pplid', :controller => 'person', :action => 'ppledit'
	match 'pplupdate', :controller => 'person', :action => 'pplupdate'
	match 'pplallshow', :controller => 'person', :action => 'personallshow'
	match 'peoplesearch', :controller => 'person', :action => 'peoplesearch'
	match 'peopleskillsearch', :controller => 'person', :action => 'peopleskillsearch'
	match 'peopleDisplayByPageRange', :controller => 'person', :action => 'peopleDisplayByPageRange'
	match 'peopleSkillViewSearch', :controller => 'person', :action => 'peopleSkillViewSearch'

	match 'spsave', :controller => 'skill', :action => 'spsave'
	match 'spshow', :controller => 'skill', :action => 'spshow'
	match 'sgcreate', :controller => 'skill', :action => 'sgcreate'
	match 'sgsave', :controller => 'skill', :action => 'sgsave'
	match 'sgshow', :controller => 'skill', :action => 'sgshow'
	match 'sgdisplay', :controller => 'skill', :action => 'sgdisplay'
	match 'spcreate', :controller => 'skill', :action => 'spcreate'
	match 'spdisplay', :controller => 'skill', :action => 'spdisplay'
	match 'skilldestroy', :controller => 'skill', :action => 'skilldestroy'
	match 'usrskilledit/:sid&:gid&:pid', :controller => 'skill', :action => 'usrskilledit'
	match 'usrskillupdate', :controller => 'skill', :action => 'usrskillupdate'
	match 'grpskilledit/:sid&:gid', :controller => 'skill', :action => 'grpskilledit'
	match 'groupskilledit/:sid&:gid', :controller => 'skill', :action => 'groupskilledit'
	match 'grpskillupdate', :controller => 'skill', :action => 'grpskillupdate'
	match 'skillsearch', :controller => 'skill', :action => 'skillsearch'	
	match 'skillviewsearch', :controller => 'skill', :action => 'skillviewsearch'
	match 'allGroupSkills', :controller => 'skill', :action => 'allGroupSkills'
	match 'allPersonSkills', :controller => 'skill', :action => 'allPersonSkills'

	match 'showAllSkills', :controller => 'skill', :action => 'showAllSkills'
	

   root :to => 'organization#index'

end

app/models/group.rb
class Group < ActiveRecord::Base

	
  belongs_to :organization
	has_many :people, :dependent => :destroy
	has_many :skills, :dependent => :destroy
  attr_accessible :name
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
	def grpcreate
		@org = Organization.all
		render :file => "app/views/group/grpcreate.html.erb"
	end
	def grpsave
		@organization = Organization.find(params[:orgsel])
		@group = @organization.groups.new
		@group.name = params[:grpname]
		if(@group.save)
			flash[:notice] = 'Group Successfully Created'
			@grp = Group.order("id").page(params[:page]).per(2)
			redirect_to  :action => 'groupallshow'
		end
	end
	def search
		@organization = Organization.all
		render :file => "app/views/group/grpshow.html.erb"
	end

	def groupsearch
		@organization = Organization.find(params[:id])
		@groups = @organization.groups.all
		render :partial => "groupsearchresult.html.erb"
	end

	def groupSkillSearch
		@organization = Organization.find(params[:id])
		@groups = @organization.groups.all
		render :partial => "groupskillsearchresult.html.erb"
	end
	
	def groupshow

		@grp = Group.find(params[:grpsel])
		@q = @grp.people.search(params[:q])
		@prsn = @q.result.order("id").page(params[:page]).per(2)
		render :file => "app/views/group/grpdisplay.html.erb"
	end

	def grpedit
		@org = Organization.all
		@grp = Group.find(params[:grpid])
		@@gr1 = @grp
		render :file => "app/views/group/grpeditview.html.erb"
	end

	def grpupdate
		@@gr1.organization_id = params[:orgsel]
		@@gr1.name = params[:grpname]
		if(@@gr1.save)
			flash[:notice] = 'Group Successfully Updated'
			@grp = Group.order("name").page(params[:page]).per(2)			
			render :file => 'app/views/group/groupallshow.html.erb'		
		end
	end

	def grpdestroy
		grp = Group.find(params[:id])
		grp.destroy
		render :file => 'app/views/group/remsuccess.html.erb'
			
	end

	before_filter :set_search

	def set_search
    #render :text => params.inspect and return
		@search=Group.search(params[:q])
		@search1 = Person.search(params[:q])
	end

	def groupallshow
		@q = Group.search(params[:q])
		@grp = @q.result.order("id").page(params[:page]).per(3)
		render :file => "app/views/group/groupallshow.html.erb"
	end

	def groupDisplayRange
		@grp = Group.order("name").page(params[:page]).per(params[:id])
		render :partial => "groupDisplayRange.html.erb"
	end
end

app/helpers/group_helper.rb
module GroupHelper
end

app/views/group/_groupDisplayRange.html.erb
<table class='table table-striped table-hover' >
			<tr>
				<th> Organization Id: </th>
				<th> Group Id </th>
				<th> Name:</th>
				<th colspan='2' class='opth'>Action</th>
			</tr>

		<% @grp.each do |s| %>
			<tr>
				<td> <%= s.organization_id %>
				<td> <%= s.id %> </td>
				<td> <%= s.name %> </td>
				<td class='optd' id = 'optd1'> <a href='/grpedit/<%= s.id %>' title='Click to Edit the Organization' name='edit' > <img src='assets/tab_edit.png'> </a> </td>
				<td class='optd1' id=<%= s.name %>> <%= link_to image_tag('/assets/delete.png', :class=>s.id, :id=>'opdelete'), grpdestroy_path(), :title => 'Click to Delete the Organization', :class=> s.id, :id=> 'opdelete' %> </td>
			</tr>
			<% end %>
		</table>

app/views/group/_groupsearchresult.html.erb
<html>
<head>
	<script>
		$(document).ready(function() { 
			$('#groupfind').change(function() { 
							var idval = $(this).val();
							$.ajax({
								url:'/peoplesearch',
								data: {id:idval},
								dataType:"html",
								success: function(data) { 
									$('.peoplesearch').html(data)
								},
								error: function(data) {
									//alert('error Occurred')
								}
							});
			});	
		});
	</script>
</head>
<body>
<select name='grpsel' class='span2' id='groupfind'>
	<option value=''> Select Group </option>
	<%= @groups.each do |g| %>
		<option value= <%= g.id %>> <%= g.name %>  </option>
	<% end %>
</select>
</body>
</html>



	

app/views/group/_groupskillsearchresult.html.erb
<html>
<head>
	<script>
		$(document).ready(function() { 
			$('#groupfind').change(function() { 
							var idval = $(this).val();
							$.ajax({
								url:'/peopleSkillViewSearch',
								data: {id:idval},
								dataType:"html",
								success: function(data) { 
									$('.peoplesearch').html(data)
								},
								error: function(data) {
									//alert('error Occurred')
								}
							});
			});	
		});
	</script>
</head>
<body>
<select name='grpsel' class='span2' id='groupfind'>
	<option value=''> Select Group </option>
	<%= @groups.each do |g| %>
		<option value= <%= g.id %>> <%= g.name %>  </option>
	<% end %>
</select>
</body>
</html>



	

app/views/group/groupallshow.html.erb
<html>
	<head>
	
		  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
		  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
		  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
		  <script>
				$('document').ready(function(){
				
				$('.optd1 img').click(function(e){
						
					e.preventDefault();
					var va = $(this).attr("class");
					$( "#dialog-confirm" ).dialog({
					  resizable: false,
					  height:180,
					  width:400,
					  modal: true,
					  buttons: {
						"Delete": function() {
						  $( this ).dialog( "close" );
							//return true;
							  $.ajax({
				        		url: "/grpdestroy",
								data: {id: va},
				        		success: function (data) {
								$("#myid").html("successfully deleted");
								$("#myid1").html("");
				        		}
				    		   });

						 },
						"No": function() {
						  $( this ).dialog( "close" );
							return false;
						  }
						  }
					  }); 
				});				
					

				$('#pagepershow').change(function() { 
						var selectedPageRange = $(this).val()
						if((selectedPageRange == 'null')||(selectedPageRange == ''))			
						{
						}
						else
						{
							$.ajax({
								url:'/groupDisplayRange',
								data: {id:selectedPageRange},
								dataType: 'html',
								success: function(data) {
									$('#groupDisplayRange').html(data)
								},
								error: function(data) {
									alert('error Occurred')
								}
							});
						}
				});
		

});
		  </script>

<style>
	table {
		width:300px !important;
	}
</style>

	</head>
	<body>
		
		<div id='myid1'>
		 <% if flash[:notice] %>
		    <div class="alert alert-success">  
  					<a class="close" data-dismiss="alert">&times;</a>  
					  <strong>Success!</strong> <%= flash[:notice] %>
			</div>  
		 <% end %>
			<br />
<div class='btn'> <%= link_to 'Create Group',  gcreate_path %> </div> <br /> <br />


	
		


		<div id='groupDisplayRange'>
		<table class='table table-striped table-hover' >
		  <%= search_form_for @search, :url=>'grpallshow' do |f| %>
			<tr>
				<td id='gname'> <%= f.text_field :name_cont, :placeholder => 'Filter', :class=>'filterbox' %> </td>			<td id='mptycolumn' colspan='2'> <%= f.submit 'Filter', :class=>'btn btn-primary filterbutton' %> </td>
			</tr>	
		  <% end %>	
			
			<tr>
				<th> <%= sort_link(@q, :name, "Group Name") %> </th>
				<th colspan='2' class='opth'>Action</th>
			</tr>

		<% @grp.each do |s| %>
			<tr>
				<td> <%= s.name %> </td>
				<td class='optd' id = 'optd1'> <a href='/grpedit/<%= s.id %>' title='Click to Edit the Organization' name='edit' > <img src='assets/tab_edit.png'> </a> </td>
				<td class='optd1' id=<%= s.name %>> <%= link_to image_tag('/assets/delete.png', :class=>s.id, :id=>'opdelete'), grpdestroy_path(), :title => 'Click to Delete the Organization', :class=> s.id, :id=> 'opdelete' %> </td>
			</tr>
			<% end %>

		




		</table>
		</div>
	</div>
<span class='paginationbg'> <%= paginate @grp %> </span>
<br />
<div id="dialog-confirm" title="Do you wanna Delete this?">
  <p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>This item will be permanently deleted and cannot be recovered. Are you sure?</p> </div>

	</body>
</html>

app/views/group/grpcreate.html.erb
<html>
	<head>
		<style>
			.span3 {
				position:absolute;
				right:420px;
			}
		</style>
		<script type='text/javascript'>
				function validateMe() {
					nameval = document.getElementById('grpname')
					namevalue = nameval.value
					if((namevalue == 'null') || (namevalue == ''))
						{
							document.getElementById('errormsg').innerHTML = 'Please Fill the Name'
								return false;
						}
						else {
							document.getElementById('errormsg').innerHTML = ''
							return true;
						}
					}			
		</script>
	</head>
	<body>
<div class='btn'>	<%= link_to 'View Users', search_path %> </div> <br /> <br />
		<%= form_tag({:action => "grpsave" }, :id => "form_id", :name => 'group', :class => 'form-horizontal', :onsubmit => 'return validateMe()')  do %>
				<div class="control-group">
					<label class="control-label" for="inputId">Organization :</label>
					<div class="controls">
						<select name= 'orgsel' class = 'span2'>
							<% @org.each do |o| %>
								<option value=<%= o.id %>> <%= o.name %> </option>
							<% end %>
						</select>
					</div>
			    </div>
				<div class="control-group">
					<label class="control-label" for="inputName">Group Name: </label>
					<div class="controls">
					  <input type="text" name ='grpname' id="grpname" placeholder="Group Name"> <span id='errormsg'> </span>
					</div>
				</div>
				<div class='span3'>
				<%= submit_tag "Save", :id => "uploadid", :class => 'btn btn-primary'%>
				</div>
		<% end %>

	<br />

	</body>
</html>

app/views/group/grpdisplay.html.erb
<html>
	<head>

		<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
		  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
		  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
		  <script>
				$('document').ready(function(){
					
						
				$('.optd1 img').click(function(e){
					
					$('#dialog-confirm').show();
					e.preventDefault();
					var va = $(this).attr("class");
					$( "#dialog-confirm" ).dialog({
					  resizable: false,
					  height:180,
					  width:400,
					  modal: true,
					  buttons: {
						"Delete": function() {
						  $( this ).dialog( "close" );
							//return true;
							  $.ajax({
				        		url: "/ppldestroy",
								data: {id: va},
				        		success: function (data) {
								$("#myid1").html(" ");
								$("#myid").html(" successfully deleted");
								
							   
				        		}
				    		   });

						 },
						"No": function() {
						  $( this ).dialog( "close" );
							return false;
						  }
						  }
					  }); 
				});				
						

});
		  </script>
	</head>

	<body>
	<div id='myid1'>
		<h1>Listing All Users under Group</h1>

		<div class='pull-right'>
			<%= link_to 'Add Person', pplcreate_path, :class=>'btn' %>
		</div>

 		<%= search_form_for @search1, :url=>'groupshow'  do |f| %>
				 <div class="field">
					 <%= f.hidden_field :people_group_id_eq, :value => @grp.id , :name => 'grpsel' %>
					 <%= f.text_field :group_name_or_name_cont, :placeholder => 'Total Filter', :class=>'filterbox'  %>
	 			  	 <%= f.submit 'Filter', :class=>'btn btn-primary filterbutton' %>
				  </div>
		<% end %>
		 
		<table class='table table-stiped table-hover'>

		<%= search_form_for @search1, :url=>'groupshow'  do |f| %>
			<tr>
				<%= f.hidden_field :people_group_id_eq, :value => @grp.id , :name => 'grpsel' %>
				<td id='gname'> <%= f.text_field :group_name_cont, :placeholder => 'Filter', :class=>'filterbox' %> </td> 
				<td id='pname'> <%= f.text_field :fname_cont, :placeholder => 'Filter', :class=>'filterbox' %> </td>
				<td id='mptycolumn' colspan='2'> <%= f.submit 'Filter', :class=>'btn btn-primary' %> </td>
			</tr>	
		  <% end %>	

		  <tr>
			<th> <%= sort_link(@search, :group_name, "Group Name:", {action: 'groupshow', grpsel: @grp.id} ) %> </th>
			<th> <%= sort_link(@search, :fname, "Person Name:", {action: 'groupshow', grpsel: @grp.id} ) %> </th>
			<th class='opth' colspan='2'> Action </th>
		  </tr>
		 
		<% @prsn.each do |p| %>
		  <tr>
			<td> <%= @grp.name %> </td>
			<td><%= p.fname %></td>
			<td class='optd'> <a href='/ppledit/<%= p.id %>' title='Click to Edit the User' > <img src='assets/tab_edit.png'> </a> </td>
						<td class='optd1' id=<%= p.fname %>> <%= link_to image_tag('/assets/delete.png', :class=>p.id, :id=>'opdelte'+p.id.to_s),ppldestroy_path(:id => p.id), :title=>'Click to Delete the User', :class=>p.id, :id=>'opdelete' %> </td>
		  </tr>
		<% end %>


		</table>
	</div>
	<%= paginate @prsn %>

		<div id="dialog-confirm" title="Do you wanna Delete this?">
  <p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>This item will be permanently deleted and cannot be recovered. Are you sure?</p> </div>
		<br/ >
		<div class='btn'>	<%= link_to 'Back', search_path%> </div>
	</body>

app/views/group/grpeditview.html.erb
<html>
	<head>
		<style>
			.span3 {
				position:absolute;
				right:420px;
			}
		</style>
		<script type='text/javascript'>
				function validateMe() {
					nameval = document.getElementById('grpname')
					namevalue = nameval.value
					if((namevalue == 'null') || (namevalue == ''))
						{
							document.getElementById('errormsg').innerHTML = 'Please Fill the Name'
								return false;
						}
						else {
							document.getElementById('errormsg').innerHTML = ''
							return true;
						}
					}			
		</script>
	</head>
	<body>
		<%= form_tag({:action => "grpupdate" }, :id => "form_id", :name => 'group', :class => 'form-horizontal', :onsubmit => 'return validateMe()')  do %>
				<div class="control-group">
					<label class="control-label" for="inputId">Organization Id:</label>
					<div class="controls">
						<select name= 'orgsel' class = 'span2'>
							<% @org.each do |o| %>
								<option value=<%= o.id %>> <%= o.id %> <%= o.name %> </option>
							<% end %>
						</select>
					</div>
			    </div>
				<div class="control-group">
					<label class="control-label" for="inputName">Group Name: </label>
					<div class="controls">
					  <input type="text" name ='grpname' id="grpname" value=<%= @grp.name %>> <span id='errormsg'> </span>
					</div>
				</div>
				<div class='span3'>
				<%= submit_tag "Update", :id => "uploadid", :class => 'btn btn-primary'%>
				</div>
		<% end %>
<br />
<%= link_to 'Back', oview_path %>
	</body>
</html>

app/views/group/grpshow.html.erb
<html>
	<head>
		<script>
			$(document).ready(function() {
				$('#organizationselect').change(function() { 
					var idval = $(this).val()
					 $.ajax({
				        url: "/groupsearch",
						data: {id: idval},
						dataType: 'html',
						success: function(data) {
							$(".groupsearch").html(data);							
				        },
						error: function(data) {
							alert('error');
						}
				     });
				});
			});
		</script>
	</head>
	<body>
		<div class='btn'> <%= link_to 'Create Group', gcreate_path %> </div> <br /> <br />
		<%= form_tag({:action => "groupshow" }, :name => 'group', :class=>'form-horizontal')  do %>

			<div class="control-group">
					<label class="control-label" for="inputId">Organization :</label>
					<div class="controls">
							<select name='grpsel' class='span2' id='organizationselect'>
								<option value=''> Select Organization </option>
									<% @organization.each do |o| %>
								<option value=<%= o.id %>> <%= o.name %> </option>
									<% end %>
							</select>
					  </div>
			    </div>
			<div class="control-group">
					<label class="control-label" for="inputId">Group :</label>
					<div class="controls groupsearch">
							<select name='grpsel' class='span2' disabled='disabled'>
								<option value=''> </option>
							</select>
					  </div>
			    </div>

		&nbsp;&nbsp; <%= submit_tag "Search", :id => "uploadid", :class => 'btn btn-primary'%>
		<% end %>	
	</body>
</html>

app/views/group/remsuccess.html.erb
<h1> Success fully Removed </h1>

<br />
	<%= link_to 'Create New', gcreate_path%>

app/views/group/success.html.erb
<h1> Success fully Created </h1>

<br />
	<%= link_to 'Create New', gcreate_path%>

app/views/group/upsuccess.html.erb
<h1> Updated Successfully.... </h1>

<br />
	<%= link_to 'Create New', gcreate_path%>